default:
  image: node:22
  before_script:
    - npm install

test:
  stage: test
  script:
    - npm run-script download_jar
    - npm run-script package
  artifacts:
    expire_in: 1 week
    paths:
      - prob-*.vsix
  cache:
    paths:
      - node_modules

deploy:snapshot:
  stage: deploy
  only:
    - develop@general/stups/b_language_extension
  needs:
    - test
  before_script:
    - npm install
    - apt-get update && apt-get install -y --no-install-recommends lftp openssh-client
  script: LFTP_PASSWORD="${DEPLOY_PASSWORD}" lftp -c "set cmd:fail-exit true; set sftp:auto-confirm true; open --user ${DEPLOY_USERNAME} --env-password sftp://${DEPLOY_HOST}/${DEPLOY_REMOTE_BASEDIR}/downloads/vscode_plugin/snapshot/; mput -e prob-*.vsix"

deploy:release:
  stage: deploy
  only:
    - release@general/stups/b_language_extension
  needs:
    - test
  before_script:
    - npm install
    - apt-get update && apt-get install -y --no-install-recommends lftp openssh-client
  script:
    # token given by VSCE_PAT
    - npm exec -- vsce publish --packagePath prob-*.vsix
    # token given by OVSX_PAT
    - npm exec -- ovsx publish prob-*.vsix
    - LFTP_PASSWORD="${DEPLOY_PASSWORD}" lftp -c "set cmd:fail-exit true; set sftp:auto-confirm true; open --user ${DEPLOY_USERNAME} --env-password sftp://${DEPLOY_HOST}/${DEPLOY_REMOTE_BASEDIR}/downloads/vscode_plugin/; mput -e prob-*.vsix"
